import './styles/globals.css'
import { Inter } from 'next/font/google'
import NavShops from './components/NavShops'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
        <div className='w-full h-full'>
          <header />
         <div className='flex justify-around flex-wrap grow py-10'>
         <aside className='block p-3'><NavShops/></aside>
            {children}
          </div>
          <footer />
        </div>
      </body>
    </html>
  )
}
