"use client"
import './styles/globals.css'
import { Inter } from 'next/font/google'
import getNewPizzaId from './getLib/getNewPissaId'

// import { useState, useEffect } from 'react';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children}) {
  
  
  //  const { pizza } = params;
  //  console.log('pizza', id)
// const {_id}=pizza
  // console.log('getNewPizza', getNewPizzaId)
 
  return (
    <html lang="en">
    
      <body className={inter.className}>
        <div className='w-full h-full'>
          <header />
         <div className='flex justify-around flex-wrap grow py-10'>
            {/* <aside className='block p-3'><NavShops/></aside> */}

            
            {children}
          </div>
          <footer />
        </div>
      </body>
    </html>
  )
}
